### ISSUE TITLE
Error flattening models using R410A refrigerant

### ISSUE THREAD

**Issue by elcoo** [UdK-VPT/BuildingSystems#131]
Flattening models using the R410A refrigerant is leading to compile errors. Compiling the R410A_dSpecificVolumeVap_pT Validation file for example returns this error:

```
[1] 10:51:01 Übersetzung Fehler
[BuildingSystems.Media.Refrigerants.R410A.specificVolumeVap_pT: 40:3-40:35]: Variable A not found in scope BuildingSystems.Media.Refrigerants.R410A.specificVolumeVap_pT.

[2] 10:51:01 Übersetzung Fehler
[BuildingSystems.Media.Refrigerants.R410A.dSpecificVolumeVap_pT: 32:3-32:75]: Class BuildingSystems.Media.Refrigerants.R410A.specificVolumeVap_pT not found in scope BuildingSystems.Media.Refrigerants.R410A.dSpecificVolumeVap_pT (looking for a function or record).
```

Trying to compile the "ScrollWaterToWater_OneRoomRadiator" Heatpump-Example leads to this error:
```
[4] 10:57:26 Übersetzung Fehler
[BuildingSystems.Media.Refrigerants.R410A.specificIsobaricHeatCapacityVap_Tv: 42:3-42:35]: Variable A not found in scope BuildingSystems.Media.Refrigerants.R410A.specificIsobaricHeatCapacityVap_Tv.

[5] 10:57:26 Übersetzung Fehler
[BuildingSystems.Media.Refrigerants.R410A.isentropicExponentVap_Tv: 20:3-20:90]: Class BuildingSystems.Media.Refrigerants.R410A.specificIsobaricHeatCapacityVap_Tv not found in scope BuildingSystems.Fluid.HeatPumps.Compressors.ScrollCompressor$heaPum$com.ref.isentropicExponentVap_Tv (looking for a function or record).
```
I compiled these examples using OMEdit 1.12.0

**Comment by thorade** [comment]
These models haven been developed in [IBPSA](https://github.com/ibpsa/modelica-ibpsa), we just copied them.
A full list of copied files is here:
https://github.com/UdK-VPT/BuildingSystems/blob/master/BuildingSystems/.copiedFiles.txt

The IBPSA library gets tested by the OpenModelica developers continuously here:
https://libraries.openmodelica.org/branches/master/IBPSA_latest/IBPSA_latest.html

The model has to be fixed in IBPSA, because it will be copied to other libraries as well. It could also be an OpenModelica problem, because all examples have been tested successfully in Dymola and JModelica. So, closing it here, but could you please open a ticket here:
https://github.com/ibpsa/modelica-ibpsa/issues
