### ISSUE TITLE
Building Simulation with Thermal Power as input

### ISSUE THREAD

**Issue by sohertz** [UdK-VPT/BuildingSystems#152]
Hi, 

I started working with BuildingSystems on OpenModelica. Using the current "BuildingTemplates" I have created some new buildings (for instance 3 rooms in a row and 1 corridor with all the walls, windows, floor and ceiling) and following your "Examples" I am also able to simulate them with some weather data: everything works fine and the modeling components are really good, with the templates, one understands quite easily how it works and how to combine them.

My problem is: currently I am simulating the building thermal response with some temperature set point in each room and the simulation gives me back: the required thermal power to reach the temperature setpoint. But now, I would like to know what is the thermal response of the rooms for a given injected thermal power (so basically, the other way around). But I cannot find, if there is already some existing interfaces for that (I see I can extract the rooms temperatures) but is there any input to "inject" some thermal power as input of each room/zone? I could not find it in the examples... Do you have any suggestion on the matter?

**Comment by carlesRT** [comment]
Hi Sohertz, 

I haven't work much with the building models but I think i might help you... 
One option would be to adapt (create a new one) building template <code>Buildings.Zones.ZoneTemplateAirvolumeMixed</code> where you instead of using fast-PI controllers (see instances <code>coolingLoad</code> and <code>heatingLoad</code>) you add your own heating system for the room. 
How exactly you do depends on your needs. But those are the components keeping the room temperature within the set point values, i.e. the ones you need to adapt.

**Comment by sohertz** [comment]
To anyone, who could be interesting with the solution: you may use the current building templates available in the library (under Buildings.BuildingTemplates) and change two inputs: `heatSources` should be set as true and `calcIdealLoads` to false. These inputs are used in the `ZoneTemplateAirvolumeMixed` model (your zones). Please note that this require the adaptation of the `connect` blocks.
