### ISSUE TITLE
Pedantic Error when using Pump with MSL.Water

### ISSUE THREAD

**Issue by Heineken** [UdK-VPT/BuildingSystems#40]
When running `BuildingSystems.Fluid.Movers.FlowControlled_m_flow` with MSL.Water in pedantic mode I get:

`The value=0 not in range [611.657,1e+008] for variable pump.preSou.dp_start.``

Example:
```
model Source2Pump_
//  replaceable package Medium = Modelica.Media.Water.ConstantPropertyLiquidWater;
    replaceable package Medium =  Modelica.Media.Water.WaterIF97OnePhase_ph;

  inner Modelica.Fluid.System system
    annotation (Placement(transformation(extent={{-84,72},{-64,92}})));
  BuildingSystems.Fluid.Sources.Boundary_pT      boundary(
    redeclare package Medium = Medium,
    nPorts=1) annotation (Placement(transformation(
        extent={{-10,-10},{10,10}},
        rotation=0,
        origin={-70,14})));
  BuildingSystems.Fluid.Sources.Boundary_pT bou(
    redeclare package Medium = Medium,
    nPorts=1) annotation (Placement(transformation(
        extent={{-10,-10},{10,10}},
        rotation=180,
        origin={60,14})));
  BuildingSystems.Fluid.Movers.FlowControlled_m_flow pump(
    redeclare package Medium = Medium,
    m_flow_nominal=1,
    inputType=BuildingSystems.Fluid.Types.InputType.Constant)
                      annotation (Placement(transformation(
        extent={{-10,10},{10,-10}},
        rotation=0,
        origin={16,14})));
equation 

  connect(pump.port_b, bou.ports[1])
    annotation (Line(points={{26,14},{38,14},{50,14}}, color={0,127,255}));
  connect(boundary.ports[1], pump.port_a)
    annotation (Line(points={{-60,14},{-28,14},{6,14}}, color={0,127,255}));
end Source2Pump_;
```

**Comment by thorade** [comment]
That model was developed in Annex60, we just copied it from there, see
https://github.com/UdK-VPT/BuildingSystems/blob/master/BuildingSystems/.copiedFiles.txt
https://github.com/UdK-VPT/BuildingSystems/blob/master/BuildingSystems/.copiedFiles.txt#L433

The problem seems to be related to the difference between the SIunit types AbsolutePressure and PressureDifference. An AbsolutePressure=0 is physically impossible, while PressureDifference can be 0 or even negative. dp_start should probably be of type PressureDifference.
You should check what type is used and where the variable is declared, then file an issue in the Annex60 issue tracker and send a Pull Request with a fix. Once the issue is solved in Annex60, we can re-run the integration scripts to copy the latest Annex code into the BuildingSystems library.

**Comment by Heineken** [comment]
That was helpful. 

Done: https://github.com/iea-annex60/modelica-annex60/pull/403
